# Funbox Users config
---
# Hostname the server listens on.
# If proxying through Apache, this should probably be '127.0.0.1'.
# Set to '0.0.0.0' to make publicly available (note: DO NOT FUCKING DO THIS)
host: '127.0.0.1'
port: 5000

# Name used in emails and such
service_name: 'Funbox'

# This should probably stay disabled
debug: false

# See https://flask-limiter.readthedocs.io/en/stable/#ratelimit-string
rate_login: '10/hour;100/day'
rate_reset: '10/day'
rate_confirm: '6/hour;10/day'

# Not yet implemented
log:
  level: info
  file: dev.log
  size: 50MB
  keep: 10
  #format: '' # Not sure if this is even reasonable

# Currently just set for testing with https
# TODO might not need this with Apache
# NOTE In dev, toggling https when the browser has an active cookie can
# cause the server to fail to give the browser a new cookie. The work-around is
# to toggle https back to what it was before, reload, then clear the cookie.
# Also, https can just be really frickin slow, for some reason.
# Finally, enabling this will make *all* the server tests fail.
https:
  enabled: false
  cert_file: 'cert.pem'
  key_file: 'key.pem'
